lang:
  no-permission: "&cYou don't have permission to do that."
  player-only: "&cOnly players can do that."

commands:
  hello:
    - "[broadcast] hello"
    - "[console] say hello"

menus:
  recipes:
    title: "Recipes"
    size: 45
    search:
      enabled: true
      title: "Search %search%"
      lines:
        - "%search%"
        - "----------------"
        - "Please enter a"
        - "search result."
      material: OAK_SIGN

      item:
        material: OAK_SIGN
        data: 0
        name: "&bSearch"
        lore:
          - "&aClick to search for recipe"
        slot: 4
        glowing: false

    items:
      1:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 0
      2:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 1
      3:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 2
      4:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 3
      5:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 4
      6:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 5
      7:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 6
      8:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 7
      9:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 8
      10:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 9
      11:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 17
      12:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 18
      13:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 26
      14:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 27
      15:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 35
      16:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 36
      17:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 37
      18:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 38
      19:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 39
      20:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 40
      21:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 41
      22:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 42
      23:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 43
      24:
        material: BLACK_STAINED_GLASS_PANE
        name: " "
        slot: 44
    clickable-items:
      next:
        material: ARROW
        name: "&aNext Page"
        lore:
          - "&7Click to go to the next page."
        slot: 44
      previous:
        material: ARROW
        name: "&aPrevious Page"
        lore:
          - "&7Click to go to the previous page."
        slot: 36
